package com.databricks.mlflow.client.objects;

import com.fasterxml.jackson.annotation.JsonProperty;

// Autogenerated on 2018-08-03 09:56:31 UTC

public class CreateRunRequest { 
    public CreateRunRequest() {
    }
    public CreateRunRequest(
            String experimentId,
            String runName,
            String sourceType,
            String sourceName,
            long startTime,
            String userId)  {
        this.experimentId = experimentId;
        this.runName = runName;
        this.sourceType = sourceType;
        this.sourceName = sourceName;
        this.startTime = startTime;
        this.userId = userId;
    }
    @JsonProperty("experiment_id")
    private String experimentId; 
    public String getExperimentId() { return experimentId; }
    public void setExperimentId(String experimentId) { this.experimentId = experimentId; }
 
    @JsonProperty("run_name")
    private String runName; 
    public String getRunName() { return runName; }
    public void setRunName(String runName) { this.runName = runName; }
 
    @JsonProperty("source_type")
    private String sourceType; 
    public String getSourceType() { return sourceType; }
    public void setSourceType(String sourceType) { this.sourceType = sourceType; }
 
    @JsonProperty("source_name")
    private String sourceName; 
    public String getSourceName() { return sourceName; }
    public void setSourceName(String sourceName) { this.sourceName = sourceName; }
 
    @JsonProperty("start_time")
    private long startTime; 
    public long getStartTime() { return startTime; }
    public void setStartTime(long startTime) { this.startTime = startTime; }
 
    @JsonProperty("user_id")
    private String userId; 
    public String getUserId() { return userId; }
    public void setUserId(String userId) { this.userId = userId; }

    @Override
    public String toString() {
        return
              " experimentId=" + experimentId 
            + " runName=" + runName 
            + " sourceType=" + sourceType 
            + " sourceName=" + sourceName 
            + " startTime=" + startTime 
            + " userId=" + userId 
        ;
    }
}
