package com.databricks.mlflow.client.objects;

import com.fasterxml.jackson.annotation.JsonProperty;

// Autogenerated on 2018-08-03 03:05:37 UTC

public class ExperimentSummary {
    private String experiment_id; 
    @JsonProperty("experiment_id")
    public String getExperiment_id() { return experiment_id; }
    public void setExperiment_id(String experiment_id) { this.experiment_id = experiment_id; }
 
    private String name; 
    @JsonProperty("name")
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
 
    private String artifact_location; 
    @JsonProperty("artifact_location")
    public String getArtifact_location() { return artifact_location; }
    public void setArtifact_location(String artifact_location) { this.artifact_location = artifact_location; }

    @Override
    public String toString() {
        return
              "experiment_id=" + experiment_id 
            + " name=" + name 
            + " artifact_location=" + artifact_location 
        ;
    }
}
